In [ ]:
import pandas as pd
import numpy as np

In [ ]:
fname="/content/drive/MyDrive/f1 - Copy.xlsx"
df = pd.read_excel(f"{fname}", keep_default_na=False, header=None)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,,,,,,,,,,,...,,,,,,,,7/1/2023 11:24:31 AM,,
1,Detail Transaction Totals List for,,,,,,,,,,...,,,,,,,,,Page 1 of 20,
2,6/30/2023 to 6/30/2023,,,,,,,,,,...,,,,,,,,,,
3,Code,,Room,,Account,,,Name,,,...,,,User,,,,Time,,,Amount
4,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,151,,192,,812-550313,,,"WRIGHT, AMIE ELIZABETH",,,...,,,RRI812,,,,3:40,,,$2.23
908,,,,,,,,,,,...,,,,Total for 6/30/2023,,,,,,$227.59
909,,,,,,,,,,,...,,,,,Total for 151,,,,,$227.59
910,,,,,,,,,,,...,,,,,,,,,,
911,RRI812 - Red Roof Inn & Suites Newark - Univer...,,,,,,,,,,...,,,,,,,,,Page 20 of 20,

In [ ]:
df.drop(df.head(3).index, inplace=True)
df.drop(df.tail(2).index, inplace=True)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
3,Code,,Room,,Account,,,Name,,,...,,,User,,,,Time,,,Amount
4,,,,,,,,,,,...,,,,,,,,,,
5,150 - STATE TAX - GL Account: 299.20812.0000.2...,,,,,,,,,,...,,,,,,,,,,
6,6/30/2023,,,,,,,,,,...,,,,,,,,,,
7,150,,182,,812-072143,,,"ADAMS, DEVIN",,,...,,,RRI812,,,,3:40,,,$7.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905,151,,243,,812-546944,,,"WILLIAMS, BRIDGET",,,...,,,RRI812,,,,3:40,,,$2.10
906,151,,120,,812-139931,,,"WINDSOR, MELINDA RAE",,,...,,,RRI812,,,,3:40,,,$2.67
907,151,,192,,812-550313,,,"WRIGHT, AMIE ELIZABETH",,,...,,,RRI812,,,,3:40,,,$2.23
908,,,,,,,,,,,...,,,,Total for 6/30/2023,,,,,,$227.59
909,,,,,,,,,,,...,,,,,Total for 151,,,,,$227.59

In [ ]:
df.replace("", np.nan, inplace=True)
df.dropna(how="all", axis=1, inplace=True)
df.dropna(how="all", axis=0, inplace=True)

In [ ]:
df

,0,2,4,6,7,13,14,22,23,24,26,27,28,29
3,Code,Room,Account,NaN,Name,NaN,Comments,User,NaN,NaN,Time,NaN,NaN,Amount
5,150 - STATE TAX - GL Account: 299.20812.0000.2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6/30/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,150,182,812-072143,NaN,"ADAMS, DEVIN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.28
8,150,159,812-006829,NaN,"ANDERSON, SHAWN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905,151,243,812-546944,NaN,"WILLIAMS, BRIDGET",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.10
906,151,120,812-139931,NaN,"WINDSOR, MELINDA RAE",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.67
907,151,192,812-550313,NaN,"WRIGHT, AMIE ELIZABETH",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.23
908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 6/30/2023,NaN,NaN,NaN,NaN,$227.59
909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 151,NaN,NaN,NaN,$227.59

In [ ]:
df.reset_index(inplace=True)
df.columns = np.arange(0, len(df.columns))

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,3,Code,Room,Account,NaN,Name,NaN,Comments,User,NaN,NaN,Time,NaN,NaN,Amount
1,5,150 - STATE TAX - GL Account: 299.20812.0000.2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,6/30/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,150,182,812-072143,NaN,"ADAMS, DEVIN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.28
4,8,150,159,812-006829,NaN,"ANDERSON, SHAWN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,905,151,243,812-546944,NaN,"WILLIAMS, BRIDGET",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.10
845,906,151,120,812-139931,NaN,"WINDSOR, MELINDA RAE",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.67
846,907,151,192,812-550313,NaN,"WRIGHT, AMIE ELIZABETH",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.23
847,908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 6/30/2023,NaN,NaN,NaN,NaN,$227.59
848,909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 151,NaN,NaN,NaN,$227.59

In [ ]:
df.dropna(subset=[df.columns[-1]], inplace=True)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,3,Code,Room,Account,NaN,Name,NaN,Comments,User,NaN,NaN,Time,NaN,NaN,Amount
3,7,150,182,812-072143,NaN,"ADAMS, DEVIN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.28
4,8,150,159,812-006829,NaN,"ANDERSON, SHAWN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.60
5,9,150,123,812-133725,NaN,"ANDING, BAHEERA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.15
6,10,150,165,812-409733,NaN,"ANDRADE, HEIDYKASSANDRA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,905,151,243,812-546944,NaN,"WILLIAMS, BRIDGET",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.10
845,906,151,120,812-139931,NaN,"WINDSOR, MELINDA RAE",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.67
846,907,151,192,812-550313,NaN,"WRIGHT, AMIE ELIZABETH",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.23
847,908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 6/30/2023,NaN,NaN,NaN,NaN,$227.59
848,909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total for 151,NaN,NaN,NaN,$227.59

In [ ]:
#to remove total for text rows
df = df[~df.apply(lambda row: row.astype(str).str.contains("Total for").any(), axis=1)]
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,3,Code,Room,Account,NaN,Name,NaN,Comments,User,NaN,NaN,Time,NaN,NaN,Amount
3,7,150,182,812-072143,NaN,"ADAMS, DEVIN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.28
4,8,150,159,812-006829,NaN,"ANDERSON, SHAWN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.60
5,9,150,123,812-133725,NaN,"ANDING, BAHEERA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.15
6,10,150,165,812-409733,NaN,"ANDRADE, HEIDYKASSANDRA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,902,151,251,812-392931,NaN,"WHITE, DOROTHY",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.25
843,904,151,128,812-746676,NaN,"WHITEHOUSE,CHRISTOPHER BRYAN",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.97
844,905,151,243,812-546944,NaN,"WILLIAMS, BRIDGET",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.10
845,906,151,120,812-139931,NaN,"WINDSOR, MELINDA RAE",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.67
846,907,151,192,812-550313,NaN,"WRIGHT, AMIE ELIZABETH",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.23

In [ ]:
#To remove repeated header
header_row = df.iloc[0]
df=df[df.apply(lambda row: not row.str.strip().equals(header_row.str.strip()), axis=1)]

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
3,7,150,182,812-072143,NaN,"ADAMS, DEVIN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.28
4,8,150,159,812-006829,NaN,"ANDERSON, SHAWN",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.60
5,9,150,123,812-133725,NaN,"ANDING, BAHEERA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.15
6,10,150,165,812-409733,NaN,"ANDRADE, HEIDYKASSANDRA",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$7.13
7,11,150,222,812-643801,NaN,"AUSTIN, VERNON",NaN,STATE TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$5.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,902,151,251,812-392931,NaN,"WHITE, DOROTHY",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.25
843,904,151,128,812-746676,NaN,"WHITEHOUSE,CHRISTOPHER BRYAN",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.97
844,905,151,243,812-546944,NaN,"WILLIAMS, BRIDGET",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.10
845,906,151,120,812-139931,NaN,"WINDSOR, MELINDA RAE",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.67
846,907,151,192,812-550313,NaN,"WRIGHT, AMIE ELIZABETH",NaN,COUNTY TAX,RRI812,NaN,NaN,3:40,NaN,NaN,$2.23

In [ ]:
df.to_csv(f"{fname}.csv", header=None, index=None)